import { 
  Sprout, Leaf, Flower2, Trees, Apple, Grape, Carrot, Cherry, Citrus, Wheat, Shrub, Palmtree, TreePine,
  Flower, Sun, Cloud, Wind, Droplets, Home, Warehouse, Fence, 
  Construction, Tent, Tractor, UtilityPole, MapPin, Info, Settings, Calendar, History, Trash2, 
  Search, Plus, Minus, Check, X, ChevronRight, ChevronLeft, ChevronDown, ChevronUp, Menu, 
  MoreVertical, MoreHorizontal, Download, Upload, Share2, Copy, Edit3, Save, Printer, 
  Eye, EyeOff, Lock, Unlock, User, Users, LogOut, LogIn, Bell, Mail, Phone, Globe, 
  Heart, Star, Bookmark, Share, MessageSquare, Send, Camera, Image, Video, Music, 
  Mic, Play, Pause, SkipBack, SkipForward, Volume2, VolumeX, Wifi, Battery, 
  Clock, Watch, AlarmClock, Timer, Map, Compass, Navigation, Layers, 
  Layout, Grid, List, Table, BarChart2, PieChart, Activity, Zap, 
  Shield, Key, LockKeyhole, Fingerprint, CreditCard, Wallet, ShoppingCart, 
  ShoppingBag, Package, Truck, Gift, Coffee, Utensils, Pizza, Beer, 
  Smartphone, Tablet, Laptop, Monitor, Tv, Speaker, Headphones, 
  Gamepad2, Mouse, Keyboard, Cpu, HardDrive, Database, CloudUpload, 
  CloudDownload, Terminal, Code2, Braces, Hash, AtSign, Link, Paperclip, 
  Scissors, PenTool, Eraser, Brush, Palette, Contrast, SunMedium, 
  Moon, CloudRain, CloudLightning, CloudSnow, Thermometer, Droplet, 
  Flame, Sparkles, ZapOff, Ghost, Skull, Bug, Footprints, PawPrint, 
  Fish, Bird, Rabbit, Cat, Dog, Turtle, Snail, Shell, 
  Mountain, Trees as TreesIcon, TreePine as TreePineIcon, TreePalm, 
  Flower as FlowerIcon, Tent as TentIcon, Waves, Sunrise, Sunset, 
  Stethoscope, Briefcase, GraduationCap, Trophy, Medal, Target, 
  Flag, Anchor, Rocket, Plane, Train, Bus, Bike, Car, 
  Dumbbell, Bike as BikeIcon, Footprints as FootprintsIcon, 
  Heart as HeartIcon, Activity as ActivityIcon, 
  Stethoscope as StethoscopeIcon, Briefcase as BriefcaseIcon, 
  GraduationCap as GraduationCapIcon, Trophy as TrophyIcon, 
  Medal as MedalIcon, Target as TargetIcon, Flag as FlagIcon, 
  Anchor as AnchorIcon, Rocket as RocketIcon, Plane as PlaneIcon, 
  Train as TrainIcon, Bus as BusIcon, Bike as BikeIcon2, 
  Car as CarIcon, Dumbbell as DumbbellIcon,
  TentTree, TreeDeciduous, TreePine as TreePine2, 
  Flower2 as Flower2Icon, Shrub as ShrubIcon, 
  Clover, Wind as WindIcon, CloudRain as CloudRainIcon, 
  CloudSun, CloudMoon, CloudFog, CloudDrizzle, 
  CloudHail, CloudLightning as CloudLightning2, 
  CloudSnow as CloudSnow2, CloudOff, 
  Sun as SunIcon, Moon as MoonIcon, 
  Thermometer as ThermometerIcon, ThermometerSnowflake, 
  ThermometerSun, Droplets as DropletsIcon, 
  Droplet as DropletIcon, Waves as WavesIcon, 
  Flame as FlameIcon, Zap as ZapIcon, 
  Sparkles as SparklesIcon, ZapOff as ZapOffIcon, 
  Ghost as GhostIcon, Skull as SkullIcon, 
  Bug as BugIcon, Footprints as FootprintsIcon2, 
  PawPrint as PawPrintIcon, Fish as FishIcon, 
  Bird as BirdIcon, Rabbit as RabbitIcon, 
  Cat as CatIcon, Dog as DogIcon, 
  Turtle as TurtleIcon, Snail as SnailIcon, 
  Shell as ShellIcon, Mountain as MountainIcon, 
  Trees as TreesIcon2, TreePine as TreePineIcon2, 
  TreePalm as TreePalmIcon, Flower as FlowerIcon2, 
  Tent as TentIcon2, Waves as WavesIcon2, 
  Sunrise as SunriseIcon, Sunset as SunsetIcon, 
  Stethoscope as StethoscopeIcon2, Briefcase as BriefcaseIcon2, 
  GraduationCap as GraduationCapIcon2, Trophy as TrophyIcon2, 
  Medal as MedalIcon2, Target as TargetIcon2, 
  Flag as FlagIcon2, Anchor as AnchorIcon2, 
  Rocket as RocketIcon2, Plane as PlaneIcon2, 
  Train as TrainIcon2, Bus as BusIcon2, 
  Bike as BikeIcon3, Car as CarIcon2, 
  Dumbbell as DumbbellIcon2,
  Warehouse as WarehouseIcon, Fence as FenceIcon, 
  Construction as ConstructionIcon, Tent as TentIcon3, 
  Tractor as TractorIcon, UtilityPole as UtilityPoleIcon, 
  MapPin as MapPinIcon, Info as InfoIcon, 
  Settings as SettingsIcon, Calendar as CalendarIcon, 
  History as HistoryIcon, Trash2 as Trash2Icon, 
  Search as SearchIcon, Plus as PlusIcon, 
  Minus as MinusIcon, Check as CheckIcon, 
  X as XIcon, ChevronRight as ChevronRightIcon, 
  ChevronLeft as ChevronLeftIcon, ChevronDown as ChevronDownIcon, 
  ChevronUp as ChevronUpIcon, Menu as MenuIcon, 
  MoreVertical as MoreVerticalIcon, 
  MoreHorizontal as MoreHorizontalIcon, 
  Download as DownloadIcon, Upload as UploadIcon, 
  Share2 as Share2Icon, Copy as CopyIcon, 
  Edit3 as Edit3Icon, Save as SaveIcon, 
  Printer as PrinterIcon, Eye as EyeIcon, 
  EyeOff as EyeOffIcon, Lock as LockIcon, 
  Unlock as UnlockIcon, User as UserIcon, 
  Users as UsersIcon, LogOut as LogOutIcon, 
  LogIn as LogInIcon, Bell as BellIcon, 
  Mail as MailIcon, Phone as PhoneIcon, 
  Globe as GlobeIcon, Heart as HeartIcon2, 
  Star as StarIcon, Bookmark as BookmarkIcon, 
  Share as ShareIcon, MessageSquare as MessageSquareIcon, 
  Send as SendIcon, Camera as CameraIcon, 
  Image as ImageIcon, Video as VideoIcon, 
  Music as MusicIcon, Mic as MicIcon, 
  Play as PlayIcon, Pause as PauseIcon, 
  SkipBack as SkipBackIcon, SkipForward as SkipForwardIcon, 
  Volume2 as Volume2Icon, VolumeX as VolumeXIcon, 
  Wifi as WifiIcon, Battery as BatteryIcon, 
  Clock as ClockIcon, Watch as WatchIcon, 
  AlarmClock as AlarmClockIcon, Timer as TimerIcon, 
  Map as MapIcon, Compass as CompassIcon, 
  Navigation as NavigationIcon, Layers as LayersIcon, 
  Layout as LayoutIcon, Grid as GridIcon, 
  List as ListIcon, Table as TableIcon, 
  BarChart2 as BarChart2Icon, PieChart as PieChartIcon, 
  Activity as ActivityIcon2, Zap as ZapIcon2, 
  Shield as ShieldIcon, Key as KeyIcon, 
  LockKeyhole as LockKeyholeIcon, Fingerprint as FingerprintIcon, 
  CreditCard as CreditCardIcon, Wallet as WalletIcon, 
  ShoppingCart as ShoppingCartIcon, 
  ShoppingBag as ShoppingBagIcon, Package as PackageIcon, 
  Truck as TruckIcon, Gift as GiftIcon, 
  Coffee as CoffeeIcon, Utensils as UtensilsIcon, 
  Pizza as PizzaIcon, Beer as BeerIcon, 
  Smartphone as SmartphoneIcon, Tablet as TabletIcon, 
  Laptop as LaptopIcon, Monitor as MonitorIcon, 
  Tv as TvIcon, Speaker as SpeakerIcon, 
  Headphones as HeadphonesIcon, Gamepad2 as Gamepad2Icon, 
  Mouse as MouseIcon, Keyboard as KeyboardIcon, 
  Cpu as CpuIcon, HardDrive as HardDriveIcon, 
  Database as DatabaseIcon, CloudUpload as CloudUploadIcon, 
  CloudDownload as CloudDownloadIcon, Terminal as TerminalIcon, 
  Code2 as Code2Icon, Braces as BracesIcon, 
  Hash as HashIcon, AtSign as AtSignIcon, 
  Link as LinkIcon, Paperclip as PaperclipIcon, 
  Scissors as ScissorsIcon, PenTool as PenToolIcon, 
  Eraser as EraserIcon, Brush as BrushIcon, 
  Palette as PaletteIcon, Contrast as ContrastIcon, 
  SunMedium as SunMediumIcon, Moon as MoonIcon2, 
  CloudRain as CloudRainIcon2, 
  CloudLightning as CloudLightningIcon, 
  CloudSnow as CloudSnowIcon, CloudOff as CloudOffIcon, 
  Sun as SunIcon2, Moon as MoonIcon3, 
  Thermometer as ThermometerIcon2, 
  ThermometerSnowflake as ThermometerSnowflakeIcon, 
  ThermometerSun as ThermometerSunIcon, 
  Droplets as DropletsIcon2, Droplet as DropletIcon2, 
  Waves as WavesIcon3, Flame as FlameIcon2, 
  Zap as ZapIcon3, Sparkles as SparklesIcon2, 
  ZapOff as ZapOffIcon2, Ghost as GhostIcon2, 
  Skull as SkullIcon2, Bug as BugIcon2, 
  Footprints as FootprintsIcon3, PawPrint as PawPrintIcon2, 
  Fish as FishIcon2, Bird as BirdIcon2, 
  Rabbit as RabbitIcon2, Cat as CatIcon2, 
  Dog as DogIcon2, Turtle as TurtleIcon2, 
  Snail as SnailIcon2, Shell as ShellIcon2, 
  Mountain as MountainIcon2, Trees as TreesIcon3, 
  TreePine as TreePineIcon3, TreePalm as TreePalmIcon2, 
  Flower as FlowerIcon3, Tent as TentIcon4, 
  Waves as WavesIcon4, Sunrise as SunriseIcon2, 
  Sunset as SunsetIcon2, Stethoscope as StethoscopeIcon3, 
  Briefcase as BriefcaseIcon3, 
  GraduationCap as GraduationCapIcon3, 
  Trophy as TrophyIcon3, Medal as MedalIcon3, 
  Target as TargetIcon3, Flag as FlagIcon3, 
  Anchor as AnchorIcon3, Rocket as RocketIcon3, 
  Plane as PlaneIcon3, Train as TrainIcon3, 
  Bus as BusIcon3, Bike as BikeIcon4, 
  Car as CarIcon3, Dumbbell as DumbbellIcon3,
  TreeDeciduous as TreeDeciduousIcon,
  Clover as CloverIcon,
  TentTree as TentTreeIcon,
  TreePine as TreePineIcon4,
  TreePalm as TreePalmIcon3
} from 'lucide-react';

export const ICON_LIST = [
  { id: 'Sprout', icon: Sprout },
  { id: 'Leaf', icon: Leaf },
  { id: 'Flower2', icon: Flower2 },
  { id: 'Trees', icon: Trees },
  { id: 'Apple', icon: Apple },
  { id: 'Grape', icon: Grape },
  { id: 'Carrot', icon: Carrot },
  { id: 'Cherry', icon: Cherry },
  { id: 'Citrus', icon: Citrus },
  { id: 'Wheat', icon: Wheat },
  { id: 'Shrub', icon: Shrub },
  { id: 'Palmtree', icon: Palmtree },
  { id: 'TreePine', icon: TreePine },
  { id: 'Flower', icon: Flower },
  { id: 'Warehouse', icon: Warehouse },
  { id: 'Home', icon: Home },
  { id: 'Fence', icon: Fence },
  { id: 'Tractor', icon: Tractor },
  { id: 'TreeDeciduous', icon: TreeDeciduous },
  { id: 'Clover', icon: Clover },
  { id: 'TentTree', icon: TentTree },
];

export const ICON_MAP: Record<string, any> = {
  Sprout, Leaf, Flower2, Trees, Apple, Grape, Carrot, Cherry, Citrus, Wheat, Shrub, Palmtree, TreePine,
  Flower, Warehouse, Home, Fence, Tractor, TreeDeciduous, Clover, TentTree
};

export const GARDEN_EMOJI_CATEGORIES = [
  {
    id: 'legume',
    label: '🥕 Légumes & Herbes',
    emojis: [
      '🍅', '🍆', '🫑', '🌶️', '🥒', '🎃', '🥑', '🥕', '🥔', '🍠', '🧅', '🧄', '🫚',
      '🥬', '🥗', '🥦', '🫛', '🫘', '🌽', '🌾', '🍄', '🌿', '🌱', '🍃', '🍀', '☘️', '🪴',
      '🔴', '🟠', '🟡', '🟢', '🟣', '🟤', '⚪', '⚫', '🟩', '🟫'
    ]
  },
  {
    id: 'fruit',
    label: '🍎 Fruits & Baies',
    emojis: [
      '🍎', '🍏', '🍐', '🍑', '🍒', '🍈', '🍇', '🫒', '🍓', '🫐', '🍊', '🍋', '🍌',
      '🍉', '🍍', '🥭', '🥝', '🥥', '🥜', '🌰',
      '🔴', '🟠', '🟡', '🟢', '🟣', '⚫'
    ]
  },
  {
    id: 'autres',
    label: '🌻 Autres (Fleurs, Outils...)',
    emojis: [
      '🌻', '🌼', '🌷', '🌹', '🌺', '🌸', '💮', '🏵️', '🪷', '🪻', '💐', '🥀',
      '🌳', '🌲', '🌴', '🌵', '🎋', '🎍', '🪾', '🪵', '🍂', '🍁',
      '🐝', '🦋', '🐞', '🐛', '🐜', '🪱', '🐌', '🐸', '🦎', '🐍', '🐢', '🐦', '🦉', '🦇', '🐿️', '🦔', '🐁', '🐀', '🐇', '🦊', '🦌', '🕷️', '🕸️',
      '🧺', '🧤', '🚜', '🪨', '🏡', '🛖', '⛺', '🪜', '🪣', '🧹', '🪓', '⛏️', '⚒️', '🛠️', '⚙️', '🧱', '⛓️', '🧰', '🔧', '🔨', '🪚', '🪛', '💧', '💦', '🚰', '🚿',
      '☀️', '🌤️', '⛅', '🌥️', '☁️', '🌦️', '🌧️', '⛈️', '🌩️', '🌨️', '❄️', '⛄', '🌬️', '💨', '🌪️', '🌫️', '🌈', '☔', '🌡️', '🔥',
      '🍯', '🍷', '🍾', '🍵', '🧉', '🧃', '🍞', '🥖', '🥨', '🍲', '🥣', '🥫', '🍿', '🧂',
      '📍', '🚩', '📌', '🏷️', '🔖', '❌', '⭕', '✅',
      '🟥', '🟧', '🟨', '🟦', '🟪', '⬜', '⬛', '🔸', '🔹', '🔶', '🔷', '🔺', '🔻'
    ]
  }
].map(cat => ({ ...cat, emojis: cat.emojis.filter((v, i, a) => a.indexOf(v) === i) }));

export const GARDEN_EMOJIS = GARDEN_EMOJI_CATEGORIES.flatMap(cat => cat.emojis);
